services:
  ai-driver:
    build:
      context: ./ai-driver
    # Пробрасываем порт 8000 из контейнера на твой компьютер
    ports:
      - "8000:8000"
    # Передаем API-ключ из твоей операционной системы внутрь контейнера
    environment:
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    # Подключаем к общей внутренней сети проекта
    networks:
      - saas-network
    
  api-core:
    build:
      context: ./api-core/ApiCore/ApiCore
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  
      - ConnectionStrings__Redis=redis:6379
      - AiDriver__Url=http://ai-driver:8000
    depends_on:
      - redis
    networks:
      - saas-network

  # Кэш и очередь задач для api-core
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - saas-network

networks:
  saas-network:
    driver: bridge
